"""
main_pi.py — AEGIS-X Main Pipeline Orchestrator (Raspberry Pi 5)
================================================================
Public interface stub. Core implementation is proprietary.

Orchestrates the full real-time intercept pipeline:

  LidarDriver ──┐
                ├──► SensorFusion ──► IMMTracker ──► APNGuidance
  CameraDetector┘                                        │
                                                         ▼
                                               NetLauncher.decide()
                                                         │
                                                         ▼
                                                ArduinoBridge.send_servo()
                                                ArduinoBridge.send_command("LAUNCH")

Pipeline timing budget (13ms median, 34ms p99):
  Sensor read + sync  :  2 ms
  Detection           :  4 ms
  EKF update          :  1 ms
  Assignment          : <1 ms
  Guidance compute    :  1 ms
  Serial command      :  2 ms
  Margin              :  2 ms

Config loaded from calibration.json (generated by calibration.py).

Author : SentrixLab
Version: 17.0
License: Proprietary — contact for licensing
"""

# Default configuration — override with calibration.json values
CFG = {
    # Hardware ports
    "arduino_port":  "/dev/ttyUSB0",
    "lidar_port":    "/dev/ttyUSB1",
    "camera_index":  0,

    # Sensor config
    "hfov_deg":      62.2,
    "vfov_deg":      48.8,
    "use_yolo":      False,
    "yolo_path":     "models/drone_yolov8n.pt",

    # Servo calibration offsets (from calibration.py)
    "pan_offset":    0.0,
    "tilt_offset":   0.0,

    # Camera depth calibration
    "bbox_ref_area": 4000.0,
    "ref_depth":     2.0,

    # Guidance
    "nav_constant":  6.5,
    "net_speed":     8.0,

    # Control loop
    "loop_hz":       12.5,
}


def load_config(path: str = "calibration.json") -> dict:
    """
    Load calibration.json and merge into CFG defaults.

    Args:
        path: path to calibration JSON

    Returns:
        Merged config dict
    """
    raise NotImplementedError("Proprietary — contact SentrixLab for licensing")


def run(cfg: dict) -> None:
    """
    Start the full AEGIS-X pipeline.

    Initialises all subsystems, starts sensor threads,
    and runs the main control loop until KeyboardInterrupt.

    Args:
        cfg: config dict (from load_config or CFG defaults)
    """
    raise NotImplementedError("Proprietary — contact SentrixLab for licensing")


if __name__ == "__main__":
    cfg = load_config()
    run(cfg)
